version: '3.7'

networks:
  yearn-mainnet-fork:

services:
  ganache:
    build:
      context: .
      args:
          - WEB3_ALCHEMY_PROJECT_ID
          - ETHERSCAN_TOKEN
    ports:
      - 80:8545
    environment:
      - WEB3_ALCHEMY_PROJECT_ID
      - ETHERSCAN_TOKEN
    networks:
      - yearn-mainnet-fork
    restart: always
